name: Deploy Documentation
on:
  push: #release:
    branches: ["workflow-documentation"] #types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies for building documentation
        run: |
             python -m pip install --upgrade pip
             pip install robotframework
             pip install robotframework-docgen
             pip install visual-regression-tracker
      - name: Generate VRTLibrary documentation
        run: |
             python -m robot.libdoc VRT/ doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: 'VRTLibrary'
          path: 'doc'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: 'VRTLibrary'